#+TITLE: home.nix

* root
:PROPERTIES:
:header-args: :noweb yes
:END:

#+begin_src nix :tangle home.nix
  { config, lib, pkgs, ... }:

  let
    inherit (lib) mkIf;
    inherit (lib.lists) optionals;
    inherit (pkgs.stdenv) isDarwin isLinux;
    homeDirectory = if isDarwin then "/Users/diana" else "/home/diana";
    <<common-packages>>
    <<linux-packages>>
    <<darwin-packages>>
  in {
    <<user-info>>

    <<state-version>>

    <<home-packages>>

    <<programs>>

    <<fonts>>

    <<nix>>

    <<dconf-settings>>

    <<xdg>>
  }
#+end_src

** basics

*** user info

#+begin_quote
Home Manager needs a bit of information about you and the paths it should
manage.
#+end_quote

#+NAME: user-info
#+begin_src nix
  home.username = "diana";
  home.homeDirectory = homeDirectory;
#+end_src

*** state version

#+begin_quote
This value determines the Home Manager release that your configuration is
compatible with. This helps avoid breakage when a new Home Manager release
introduces backwards incompatible changes.

You should not change this value, even if you update Home Manager. If you do
want to update the value, then make sure to first check the Home Manager release
notes.
#+end_quote

#+NAME: state-version
#+begin_src nix
  home.stateVersion = "25.05"; # Please read the comment before changing.
#+end_src

*** dotfiles

#+begin_quote
Home Manager is pretty good at managing dotfiles. The primary way to manage
plain files is through 'home.file'.
#+end_quote

This snippet can be used at the root-level of the config. I am currently not
managing dotfiles using either of the methods below.

#+NAME: home-files
#+begin_src nix
  home.file = {
    <<fontconfig>>
  };
#+end_src

**** link to dotfiles

#+begin_quote
Building this configuration will create a copy of 'dotfiles/screenrc' in the Nix
store. Activating the configuration will then make '~/.screenrc' a symlink to
the Nix store copy.
#+end_quote


#+NAME: example-screenrc
#+begin_src nix
  ".screenrc".source = dotfiles/screenrc
#+end_src

**** set file content directly

#+begin_quote
You can also set the file content immediately.
#+end_quote

#+NAME: example-gradle-dotfile
#+begin_src nix
  ".gradle/gradle.properties".text = ''
    org.gradle.console=verbose
    org.gradle.daemon.idletimeout=3600000
  '';
#+end_src

*** environment variables

#+begin_quote
Home Manager can also manage your environment variables through
'home.sessionVariables'. These will be explicitly sourced when using a
shell provided by Home Manager. If you don't want to manage your shell
through Home Manager then you have to manually source 'hm-session-vars.sh'
located at either

 ~/.nix-profile/etc/profile.d/hm-session-vars.sh

or

 ~/.local/state/nix/profiles/profile/etc/profile.d/hm-session-vars.sh
  #
or

 /etc/profiles/per-user/diana/etc/profile.d/hm-session-vars.sh
#+end_quote

#+begin_src nix
  home.sessionVariables = { EDITOR = "emacs"; };
#+end_src

*** session path

Not part of the home manager template. I honestly don't remember why I put this
line in lol.

#+NAME: home-session-path
#+begin_src nix
  home.sessionPath =
    [ "$HOME/.nix-profile/bin" "$HOME/.nix-profile/share/applications" ];
#+end_src

** home packages

#+begin_quote
The home.packages option allows you to install Nix packages into your
environment.
#+end_quote

#+NAME: home-packages
#+begin_src nix
  home.packages = common-packages ++ optionals isLinux linux-packages
    ++ optionals isDarwin darwin-packages;
#+end_src

*** common

#+NAME: common-packages
#+begin_src nix
  common-packages = with pkgs; [
    bat
    btop
    <<email-packages>>
    <<fonts-packages>>
    graphviz # for org-roam-ui
    gnupg
    htop
    hunspell
    hunspellDicts.en_US
    hunspellDicts.pl_PL
    imagemagick
    ispell
    <<nix-packages>>
    ncdu
    pandoc
    pls
    ripgrep
    silver-searcher
    telegram-desktop
    texlab # LaTeX LSP
    tmux
    tree
    vim

    <<writeShellScriptBin>>
  ];
#+end_src

**** email

I added these packages to try to read an email exported from Proton Mail to a
~.eml~ file in emacs. However, turns out the ~.eml~ file is encrypted, so that
was for nothing. Keeping this so that in the future I have a starting point for
setting up email in emacs.

Linking a few articles that seem to be useful:

- [[https://beb.ninja/post/email/][My E-Mail configuration: Nix & Home-Manager, Notmuch & mbsync]]
- [[https://doubleloop.net/2019/09/06/emacs-mu4e-mbsync-and-protonmail/][emacs, mu4e, mbsync and ProtonMail]]

#+NAME: email-packages
#+begin_src nix
  mu
  emacs.pkgs.mu4e
#+end_src

**** fonts

#+NAME: fonts-packages
#+begin_src nix
  nerd-fonts.ubuntu-mono
#+end_src

**** nix

- ~nil~ is a nix LSP

#+NAME: nix-packages
#+begin_src nix
  haskellPackages.nixfmt
  nil
#+end_src

**** overrides

#+begin_quote
It is sometimes useful to fine-tune packages, for example, by applying
overrides. You can do that directly here, just don't forget the parentheses.
Maybe you want to install Nerd Fonts with a limited number of fonts?
#+end_quote

This is an old way of overriding nerd fonts and no longer works, but I am
leaving this here as an example of overrides.

#+NAME: overrides
#+begin_src nix
  (pkgs.nerdfonts.override {fonts = [ "FantasqueSansMono" ]; })
#+end_src

*** Linux packages

#+NAME: linux-packages
#+begin_src nix
  linux-packages = with pkgs; [
    signal-desktop

    <<linux-writeShellScriptBin>>
  ];
#+end_src

**** Linux shell scripts

#+NAME: linux-writeShellScriptBin
#+begin_src nix
  (writeShellScriptBin "hm-news" ''
    home-manager news --flake ~/dotfiles#diana.x86_64-linux
  '')
  (writeShellScriptBin "hm-switch" ''
    home-manager switch --flake ~/dotfiles#diana.x86_64-linux
  '')
#+end_src

*** macOS packages

#+NAME: darwin-packages
#+begin_src nix
  darwin-packages = with pkgs; [
    <<darwin-writeShellScriptBin>>
  ];
#+end_src

**** macOS shell scripts

#+NAME: darwin-writeShellScriptBin
#+begin_src nix
  (writeShellScriptBin "hm-news" ''
    home-manager news --flake ~/dotfiles#diana.aarch64-darwin
  '')
  (writeShellScriptBin "hm-switch" ''
    home-manager switch --flake ~/dotfiles#diana.aarch64-darwin
  '')
#+end_src
*** simple shell scripts

#+begin_quote
You can also create simple shell scripts directly inside your
configuration. For example, this adds a command 'my-hello' to your
environment:
(pkgs.writeShellScriptBin "my-hello" ''
  echo "Hello, ${config.home.username}!"
'')
#+end_quote

#+NAME: writeShellScriptBin
#+begin_src nix
  (writeShellScriptBin "full-switch" ''
    cd ~/dotfiles
    nix flake update
    home-manager switch --flake .
    cd -
  '')
  (writeShellScriptBin "hm-history" ''
    nix profile diff-closures --profile ~/.local/state/nix/profiles/home-manager
  '')
#+end_src

** programs

#+NAME: programs
#+begin_src nix
  programs = {
    <<home-manager>>

    <<alacritty>>

    <<bash>>

    <<emacs>>

    <<firefox>>

    <<ghostty>>

    <<git>>

    <<lsd>>

    <<starship>>

    <<zsh>>
  };
#+end_src

*** home manager

#+begin_quote
Let Home Manager install and manage itself.
#+end_quote

#+NAME: home-manager
#+begin_src nix
  home-manager.enable = true;
#+end_src

*** alacritty

#+NAME: alacritty
#+begin_src nix
  alacritty = {
    enable = true;
    settings = {
      font = {
        normal = {
          family = "UbuntuMono Nerd Font";
          style = "Regular";
        };
        italic = {
          family = "UbuntuMono Nerd Font";
          style = "Italic";
        };
        bold = {
          family = "UbuntuMono Nerd Font";
          style = "Bold";
        };
        bold_italic = {
          family = "UbuntuMono Nerd Font";
          style = "Bold Italic";
        };
        size = 16;
      };
    };
    theme = "ashes_light";
  };
#+end_src

*** bash

#+NAME: bash
#+begin_src nix
  bash.enable = isLinux;
#+end_src

*** emacs

#+NAME: emacs
#+begin_src nix
  emacs.enable = true;
#+end_src

*** firefox

Only enable firefox for macOS for now to not affect the current installation of
firefox on my Ubuntu laptop.

#+NAME: firefox
#+begin_src nix
  firefox = {
    enable = isDarwin;
    profiles.diana = {
      settings = {
        "browser.newtabpage.activity-stream.feeds.system.topstories" = false;
        "browser.newtabpage.activity-stream.feeds.topsites" = false;
        "browser.newtabpage.activity-stream.showSponsoredTopSites" = false;
        "browser.shell.checkDefaultBrowser" = false;
        "extensions.formautofill.addresses.enabled" = false;
        "extensions.formautofill.creditCards.enabled" = false;
        "signon.rememberSignons" = false;
      };
    };
  };
#+end_src

*** ghostty

#+NAME: ghostty
#+begin_src nix
  ghostty = {
    enable = isLinux;
    settings = { theme = "light:Catppuccin Latte,dark:Catppuccin Frappe"; };
  };
#+end_src

*** git

#+NAME: git
#+begin_src nix
  git = {
    enable = true;
    package = pkgs.gitFull;
    settings = {
      fetch.prune = true;
      github.user = "diana-anna";
      pull = { rebase = false; };
      push = { autoSetupRemote = true; };
      user.email = "17442895+diana-anna@users.noreply.github.com";
      user.name = "diana-anna";
    };
  };
#+end_src

*** lsd

#+NAME: lsd
#+begin_src nix
  lsd = {
    enable = true;
    enableBashIntegration = isLinux;
    enableZshIntegration = isDarwin;
  };
#+end_src
*** starship

#+NAME: starship
#+begin_src nix
  starship = {
    enable = true;
    settings = {
      aws.disabled = true;

      "$schema" = "https://starship.rs/config-schema.json";

      format = lib.strings.replaceStrings [ "\n" ] [ "" ] ''
        [](red)
        $os
        $username
        [](bg:peach fg:red)
        $directory
        [](bg:yellow fg:peach)
        $git_branch
        $git_status
        [](fg:yellow bg:green)
        $c
        $golang
        $haskell
        $java
        $kotlin
        $nodejs
        $php
        $python
        $rust
        [](fg:green bg:sapphire)
        $conda
        $nix_shell
        [](fg:sapphire bg:lavender)
        $time
        [ ](fg:lavender)
        $cmd_duration
        $line_break
        $character
      '';

      character = {
        disabled = false;
        success_symbol = "[❯](bold fg:green)";
        error_symbol = "[❯](bold fg:red)";
        vimcmd_symbol = "[❮](bold fg:green)";
        vimcmd_replace_one_symbol = "[❮](bold fg:lavender)";
        vimcmd_replace_symbol = "[❮](bold fg:lavender)";
        vimcmd_visual_symbol = "[❮](bold fg:yellow)";
      };

      cmd_duration = {
        show_milliseconds = false;
        format = "  in $duration ";
        style = "bg:lavender";
        disabled = false;
        show_notifications = true;
        min_time_to_notify = 45000;
      };

      directory = {
        format = "[ $path ]($style)";
        style = "bg:peach fg:crust";
        truncation_length = 5;
        truncation_symbol = "…/";
        truncate_to_repo = false;
        substitutions = {
          "Documents" = "󰈙 ";
          "Downloads" = " ";
          "Music" = "󰝚 ";
          "Pictures" = " ";
          "Developer" = "󰲋 ";
        };
      };

      git_branch = {
        symbol = "";
        style = "bg:yellow";
        format = "[[ $symbol $branch ](fg:crust bg:yellow)]($style)";
      };

      git_status = {
        style = "bg:yellow";
        format = "[[($all_status$ahead_behind )](fg:crust bg:yellow)]($style)";
      };

      line_break.disabled = true;

      nix_shell = {
        disabled = false;
        format =
          "[[ via $symbol $state \\($name\\)](fg:crust bg:sapphire)]($style)";
        style = "bg:sapphire";
        symbol = " ";
        impure_msg = "impure";
        pure_msg = "pure";
        unknown_msg = "";
      };

      os = {
        disabled = false;
        style = "bg:red fg:crust";
        symbols = {
          Alpine = "";
          Amazon = "";
          Android = "";
          Arch = "󰣇";
          Artix = "󰣇";
          CentOS = "";
          Debian = "󰣚";
          Fedora = "󰣛";
          Gentoo = "󰣨";
          Linux = "󰌽";
          Macos = "󰀵";
          Manjaro = "";
          Mint = "󰣭";
          Raspbian = "󰐿";
          RedHatEnterprise = "󱄛";
          Redhat = "󱄛";
          SUSE = "";
          Ubuntu = "󰕈";
          Windows = "";
        };
      };

      time = {
        disabled = false;
        time_format = "%R";
        style = "bg:lavender";
        format = "[[  $time ](fg:crust bg:lavender)]($style)";
      };

      username = {
        show_always = true;
        style_user = "bg:red fg:crust";
        style_root = "bg:red fg:crust";
        format = "[ $user]($style)";
      };

      c = {
        symbol = " ";
        style = "bg:green";
        format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)";
      };
      conda = {
        symbol = "  ";
        style = "fg:crust bg:sapphire";
        format = "[$symbol$environment ]($style)";
        ignore_base = false;
      };
      docker_context = {
        symbol = "";
        style = "bg:sapphire";
        format = "[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)";
      };
      golang = {
        symbol = "";
        style = "bg:green";
        format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)";
      };
      haskell = {
        symbol = "";
        style = "bg:green";
        format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)";
      };
      java = {
        symbol = " ";
        style = "bg:green";
        format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)";
      };
      kotlin = {
        symbol = "";
        style = "bg:green";
        format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)";
      };
      nodejs = {
        symbol = "";
        style = "bg:green";
        format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)";
      };
      php = {
        symbol = "";
        style = "bg:green";
        format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)";
      };
      python = {
        symbol = "";
        style = "bg:green";
        format =
          "[[ $symbol( $version)((#$virtualenv)) ](fg:crust bg:green)]($style)";
      };
      rust = {
        symbol = "";
        style = "bg:green";
        format = "[[ $symbol( $version) ](fg:crust bg:green)]($style)";
      };

      palette = "catppuccin_mocha";

      palettes = {
        catppuccin_frappe = {
          rosewater = "#f2d5cf";
          flamingo = "#eebebe";
          pink = "#f4b8e4";
          mauve = "#ca9ee6";
          red = "#e78284";
          maroon = "#ea999c";
          peach = "#ef9f76";
          yellow = "#e5c890";
          green = "#a6d189";
          teal = "#81c8be";
          sky = "#99d1db";
          sapphire = "#85c1dc";
          blue = "#8caaee";
          lavender = "#babbf1";
          text = "#c6d0f5";
          subtext1 = "#b5bfe2";
          subtext0 = "#a5adce";
          overlay2 = "#949cbb";
          overlay1 = "#838ba7";
          overlay0 = "#737994";
          surface2 = "#626880";
          surface1 = "#51576d";
          surface0 = "#414559";
          base = "#303446";
          mantle = "#292c3c";
          crust = "#232634";
        };
        catppuccin_latte = {
          rosewater = "#dc8a78";
          flamingo = "#dd7878";
          pink = "#ea76cb";
          mauve = "#8839ef";
          red = "#d20f39";
          maroon = "#e64553";
          peach = "#fe640b";
          yellow = "#df8e1d";
          green = "#40a02b";
          teal = "#179299";
          sky = "#04a5e5";
          sapphire = "#209fb5";
          blue = "#1e66f5";
          lavender = "#7287fd";
          text = "#4c4f69";
          subtext1 = "#5c5f77";
          subtext0 = "#6c6f85";
          overlay2 = "#7c7f93";
          overlay1 = "#8c8fa1";
          overlay0 = "#9ca0b0";
          surface2 = "#acb0be";
          surface1 = "#bcc0cc";
          surface0 = "#ccd0da";
          base = "#eff1f5";
          mantle = "#e6e9ef";
          crust = "#dce0e8";
        };
        catppuccin_macchiato = {
          rosewater = "#f4dbd6";
          flamingo = "#f0c6c6";
          pink = "#f5bde6";
          mauve = "#c6a0f6";
          red = "#ed8796";
          maroon = "#ee99a0";
          peach = "#f5a97f";
          yellow = "#eed49f";
          green = "#a6da95";
          teal = "#8bd5ca";
          sky = "#91d7e3";
          sapphire = "#7dc4e4";
          blue = "#8aadf4";
          lavender = "#b7bdf8";
          text = "#cad3f5";
          subtext1 = "#b8c0e0";
          subtext0 = "#a5adcb";
          overlay2 = "#939ab7";
          overlay1 = "#8087a2";
          overlay0 = "#6e738d";
          surface2 = "#5b6078";
          surface1 = "#494d64";
          surface0 = "#363a4f";
          base = "#24273a";
          mantle = "#1e2030";
          crust = "#181926";
        };
        catppuccin_mocha = {
          rosewater = "#f5e0dc";
          flamingo = "#f2cdcd";
          pink = "#f5c2e7";
          mauve = "#cba6f7";
          red = "#f38ba8";
          maroon = "#eba0ac";
          peach = "#fab387";
          yellow = "#f9e2af";
          green = "#a6e3a1";
          teal = "#94e2d5";
          sky = "#89dceb";
          sapphire = "#74c7ec";
          blue = "#89b4fa";
          lavender = "#b4befe";
          text = "#cdd6f4";
          subtext1 = "#bac2de";
          subtext0 = "#a6adc8";
          overlay2 = "#9399b2";
          overlay1 = "#7f849c";
          overlay0 = "#6c7086";
          surface2 = "#585b70";
          surface1 = "#45475a";
          surface0 = "#313244";
          base = "#1e1e2e";
          mantle = "#181825";
          crust = "#11111b";
        };
      };
    };
  };
#+end_src

*** zsh

#+NAME: zsh
#+begin_src nix
  zsh.enable = isDarwin;
#+end_src

** fonts

Needed on Debian-based systems for fonts installed with nix to be usable.

#+NAME: fonts
#+begin_src nix
  fonts.fontconfig.enable = true;
#+end_src

** nix

#+NAME: nix
#+begin_src nix
  nix = {
    package = pkgs.nix;
    settings.experimental-features = [ "nix-command" "flakes" ];
  };
#+end_src

** GNOME

To find the list of available desktop files for programs installed with
home-manager, run

#+begin_src sh
  ls ~/.nix-profile/share/applications
#+end_src

According to [[https://askubuntu.com/questions/1160737/how-to-find-desktop-file-location-for-a-particular-application][this ask Ubuntu post]], the following is where Ubuntu searches for
these ~.desktop~ files:

#+begin_quote
Multiple .desktop launchers with the same name may exist on the system. The one
that is in use depends on where it resides.

The system first searches .desktop files in your local
~/.local/share/applications directory, and then searches applications
directories that exist under the directories included in the variable
$XDG_DATA_DIRS.
#+end_quote

For some reason though, the signal desktop icon isn't coming through, even
though I've checked that its desktop file is in
~\~/.nix-profile/share/applications~. And the Telegram desktop icon is showing
up, but nothing happens when I click on it.

#+NAME: dconf-settings
#+begin_src nix
  dconf.settings = mkIf isLinux {
    "org/gnome/shell" = {
      favorite-apps = [
        "org.gnome.Terminal.desktop"
        "org.gnome.Nautilus.desktop"
        "Alacritty.desktop"
        "htop.desktop"
        "tresorit.desktop"
        "emacs.desktop"
        "firefox_firefox.desktop"
        "chromium_chromium.desktop"
        "org.telegram.desktop.desktop"
        "signal.desktop"
        "spotify_spotify.desktop"
      ];
    };
    <<org-gnome-terminal>>
  };
#+end_src

*** Terminal

Run ~dconf dump /org/gnome/terminal~ to see these settings. Need to set the
default terminal font specifically to Ubuntu Mono Nerd Font so that nerd font
icons appear for starship prompt.

#+NAME: org-gnome-terminal
#+begin_src nix
  "org/gnome/terminal/legacy/profiles:/:1d4804e8-44e6-4c2b-a37c-95789cad0e61" = {
    font = "UbuntuMono Nerd Font Mono 12";
    use-system-font = false;
    visible-name = "diana";
  };
#+end_src

** XDG

Not sure why I added this in the first place lol.

#+NAME: xdg
#+begin_src nix
  xdg.enable = false;
#+end_src
